### ISSUE TITLE
TODO Fase 1

### ISSUE THREAD

**Issue by alecava41** [filippobrugnolaro/progettoTecWeb#1]
- [x] Pagina prenotazioneIngresso (form con field evento, noleggioMoto, noleggioAttrezzatura)
- [x] Pagina prenotazioneLezione (form con field corso, noleggioMoto, noleggioAttrezzatura)
- [x] Pagina datiUtente (form modificaDati + form modificaPsw)
- [x] Homepage area riservata utente (Box con tutte prenotazioni future + ...)

- [x] Form di registrazione
- [x] Form di login

- [x] Homepage area riservata admin (...)
- [x] Pagina gestioneTracciati (box con tutti i tracciati (info + modifica/elimina) --> modifica => nuova pagina con form tracciato) (form tracciato per inserimento nuovo tracciato)
- [x] Pagina gestioneMoto (uguale a tracciati circa)
- [x] Pagina gestioneIngressi (inserimento, modifica, cancellazione)
- [x] Pagina gestioneLezione (ins, mod, eli)

![msg746322541-8135](https://user-images.githubusercontent.com/72750724/148240459-94e999e2-0169-470c-b167-53aa26e65e54.jpg)
